### ISSUE TITLE
Power BI (pbit) and errors

### ISSUE THREAD

**Issue by gjongeneel** [Azure/azure-migrate-export#1]
Hi, this seems like a very useful tool. Unfortunately, it seems not possible to use the Power BI part correctly.

I'm using the lates version on the Power BI pbit (v1.0.02161.49) and the latest version of Power BI Desktop (2.111.590.0 64-bit (November 2022)), but during startup (double click pbit file) the error occurs: 'Unable to open document. The queries were authored with a newer version of Power BI Desktop and might not work with your version. Please install the latest version to avoid errors when refreshing.'

After that I'm able to provide my BasePath and click Load.

However, then I get some questions about Privacy levels. I select Ignore Privacy Levels checks....' and then Save. The refresh of data starts and all end in 'Loading blocked by failures with other queries.'

**Comment by hvr2804** [comment]
Hello @gjongeneel, we are aware of the issue, thank you for the feedback. We will be posting a fix soon. Will update here once the fix is deployed. Thanks.

**Comment by kalrashradha** [comment]
Hey @gjongeneel , Thanks for the feedback and we are glad that you reached out to us.
What you are seeing in POwerBI is an expected behavior. The PowerBI version in your laptop is either Nov'22 or Oct'22 release. However, the latest version expected is Dec'22 release. This problem of the old version v/s new version will persist as long as you are downloading PowerBI desktop app from the web which doesn't update to the latest version automatically. We recommend that you download the PowerBI desktop app from Microsoft (App) Store which ensures and automatically updates to the latest version.

For the second issue, Privacy levels are asked as PowerBI tries to pull supportability data of Windows and SQL Server from respective Microsoft sites, you should ignore the privacy levels and click save and this should resolve the problem. If it doesn't help, you can set global privacy levels to "Ignore Privacy". Below are the steps that you need to follow to ignore privacy levels in general.

1. Click on File> Options and Settings> Options
2. Under Global, go to Privacy and select "Always Ignore Privacy Level settings", Click OK and refresh the PowerBI again.
![image](https://user-images.githubusercontent.com/64074464/207432831-ee23f9ec-5f24-454a-840e-9ccdd79577c3.png)

This will resolve the loading error of _"Query <Table Name> <Step Name>) references other queries or steps, so it may not directly access a data source. Please rebuild this data combination."_
Hope this helps !!

If you need further assistance, we can surely set up a call for the same.

**Comment by gjongeneel** [comment]
Hi, many thanks for your thorough reply. 

By using the Store version of Power BI Desktop, the message about the version is indeed gone. The 'Always ignore Privacy Level settings' option has been selected.  However, when the load of data is started, it still ends in the following:

![image](https://user-images.githubusercontent.com/18477985/207710953-ea66e197-56b3-434b-97ea-e494036821e6.png)

Setting up a call would surely be an option.

**Comment by kalrashradha** [comment]
Please share your coordinates for me to setup the call.

> Hi, many thanks for your thorough reply.
> 
> By using the Store version of Power BI Desktop, the message about the version is indeed gone. The 'Always ignore Privacy Level settings' option has been selected. However, when the load of data is started, it still ends in the following:
> 
> ![image](https://user-images.githubusercontent.com/18477985/207710953-ea66e197-56b3-434b-97ea-e494036821e6.png)
> 
> Setting up a call would surely be an option.

**Comment by kalrashradha** [comment]
I hope this has been resolved,
