### ISSUE TITLE
The procees stuck at the SQL PAAS Assessment

### ISSUE THREAD

**Issue by ekleidaras** [Azure/azure-migrate-export#19]
Hello,

I run the tool using multiple options for VMware appliance source always without customization. All tries stuck on the "SQL PAAS Assessment". It creates the SQL -Prod-AME-xxx group and then remains on the assessment creation step. 

Please find attached a screenshot with the log, the tool status along with the groups, assessments and files created on the AzMigExport directory.

![AME](https://user-images.githubusercontent.com/122875396/218984157-85a76508-fac9-4849-b521-1f8f485b34ad.jpg)

Thank you.

**Comment by hvr2804** [comment]
Hello, thank you for your response and creating this issue, the PowerShell script has some bugs, as a result of which the assessments are not being created. Since the assessments are not being created the script is stuck in a loop to get the status of the assessment. Thus, it gets stuck.

We are working on migrating the entire code from PowerShell to embedding it in UI with .NET. This should resolve this issue.

**Comment by hvr2804** [comment]
Hello @ekleidaras , we released a new version of the tool yesterday. It has a new UI and better efficiencies compared to the script. Can you please try that?

**Comment by ekleidaras** [comment]
Hello @hvr2804,  I will give it a try and share the results here. Thank you for the update!
