### ISSUE TITLE
Costs for Azure in PowerBI 

### ISSUE THREAD

**Issue by gjongeneel** [Azure/azure-migrate-export#20]
Hi,

I've tried the new version (v2.0.02242.55). This environment has 559 servers and in Power BI it shows that these will have an enormous annual cost in Azure (see bitmap). I've selected the Express workflow, currency in Euro Zone and Migrate to all IaaS. I guess (and would hope) something is not quite correct.
   
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/18477985/220917941-78c9b958-3cc3-43eb-81c8-d444df74ff0a.png">

**Comment by gjongeneel** [comment]
May be this issue is related to issue #21?

**Comment by hvr2804** [comment]
Hello @gjongeneel can you please look at the corresponding costs in Core-Report? A picture of the small set of costs and how they appear in excel should be helpful.
Thanks.

**Comment by hvr2804** [comment]
Also @gjongeneel, it would be helpful, if you could tell, what language is setup for your MS Office, is it not English?
Basically does that language have a decimal comma [,] instead of decimal point [.]?

**Comment by hvr2804** [comment]
Hello @gjongeneel, if the locale for your device is set to Dutch, that may cause, such an issue. In that locale, the thousand separator is a point [.] while decimal separator is a [,].

When you check the Core-Report excel, and see that costs are displayed with a decimal point [.] please look at the PowerBI regional settings in
Options -> Current File -> Regional Settings -> Locale.
If this value is set to Dutch, please set that to English (United States)

Images of the Core-Report and Regional settings in PowerBI would be helpful.

**Comment by hvr2804** [comment]
Thank you very much @gjongeneel, as we can see, that in the core-report excel the values are using decimal comma, so “three hundred and eighty point eight-four-one” is treated as “three hundred and eighty thousand eight hundred and forty one”.


Can I please know if you modified the decimal separator in MS Office to comma?

you can check if your system uses, decimal comma for your excel and change the same to use a decimal point here 
https://support.microsoft.com/en-us/office/change-the-character-used-to-separate-thousands-or-decimals-c093b545-71cb-4903-b205-aebb9837bd1e

**Comment by hvr2804** [comment]
Thank you very much @gjongeneel, this may be an issue with the code base not handling devices that have a non-US regional setting.

I will be looking into this

**Comment by hvr2804** [comment]
Hello @gjongeneel , thank you very much for raising this issue. It showed that there is always room for improvement.

Can you please test this hotfix. I will be providing a zip file AzMigExport_Hotfix_InvariantCulture.zip; please download, extract and please run it as you run the deployed release build.

Please look at the Core-Report and see if the cost/numeric columns still contain a comma instead of Decimal point.

**An image of the Core-Report as you observer would be really helpful.**
[AzMigExport_Hotfix_InvariantCulture.zip](https://github.com/Azure/azure-migrate-export/files/10821000/AzMigExport_Hotfix_InvariantCulture.zip)

Adding @kalrashradha , for FYI.

**Comment by hvr2804** [comment]
Hello @gjongeneel , I tried to fix this in code, however, System Presets are taking priority over presets I set in code.

PowerBI can only handle English (United States) for region settings.

To resolve this issue, please follow the
 steps below and please let me know:
1. Please open Control Panel, by typing Control Panel in the start search bar.
![ControlPanel](https://user-images.githubusercontent.com/64649937/221114939-76342fed-b2b3-4a46-befc-46d767e13899.PNG)

2. In the search bar please type "Region"
![region](https://user-images.githubusercontent.com/64649937/221114969-b53e1488-e859-4bce-99ae-9b2121830964.PNG)

3. Click on "Change date, time or number formats"
4. Click on "Additional Settings"
![RegionSettings](https://user-images.githubusercontent.com/64649937/221115000-f5ab76b2-d4ee-42a7-bb05-3cc37d1bc2a5.PNG)

5. Please select the "Decimal Symbol" as '.'
![CustomizeFormat](https://user-images.githubusercontent.com/64649937/221115020-21ab9b5b-4419-4093-a4ea-e91f80bd8e42.PNG)

6. Click on "Apply" for changes to take effect
7. Click on "Ok" on the "Customize Format" box
8. Click on "Ok" again on the "Region" box

Now when you open the Excel reports it would contain, Decimal as point, and this should also load in PBIT

**Comment by gjongeneel** [comment]
After changing the decimal symbol, it looks much better:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/18477985/221130163-1385ae63-5ab6-4b9c-b43d-3fd52326efd7.png">

However, as I actually live in the Netherlands, we need the decimal symbol to be a ',' for everyday work. It doesn't sound like a very 'global' solution that we are required to use the US format.

**Comment by hvr2804** [comment]
Thank you very much @gjongeneel , I really appreciate all the help from you today.

I appreciate the situation, of currently using the US format. However, this problem was seated a little deeper, even if I wrote decimal point, in excel, Power BI was still parsing it as decimal comma, because of system presets.

I have taken this as a work item, and am looking into the best possible way for a global resolution.

Until then, I request you to please use Decimal point instead of decimal comma.

**Comment by hvr2804** [comment]
Hello @gjongeneel , we have released a new version of Power BI template, v2.0.02249.58, this should resolve the issue you were having. Please let us know, and we can close this issue.

Thank you very much for bringing this up.
